# Generated by Django 3.2.9 on 2023-04-12 10:43

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_blog_posted_by_blog_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', help_text='Upload image of size 350 x 350', keep_meta=True, quality=70, scale=None, size=[350, 350], upload_to='blogs'),
        ),
        migrations.AlterField(
            model_name='carousal',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', help_text='Upload image of size 350 x 350', keep_meta=True, quality=70, scale=None, size=[650, 350], upload_to='carousal'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', help_text='Upload image of size 400 x 400', keep_meta=True, quality=70, scale=None, size=[500, 500], upload_to='product-img'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', help_text='Upload image of size 400 x 150', keep_meta=True, quality=70, scale=None, size=[400, 150], upload_to='offer'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', help_text='Upload image of size 400 x 400', keep_meta=True, quality=70, scale=None, size=[500, 500], upload_to='product-img'),
        ),
    ]
