# Generated by Django 3.2.9 on 2023-04-12 11:05

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20230412_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', help_text='Upload image of size 350 x 350', keep_meta=True, quality=70, scale=None, size=[1920, 1080], upload_to='blogs'),
        ),
        migrations.AlterField(
            model_name='carousal',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', help_text='Upload image of size 650 x 350', keep_meta=True, quality=70, scale=None, size=[1920, 1080], upload_to='carousal'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', help_text='Upload image of size 600 x 600', keep_meta=True, quality=70, scale=None, size=[1920, 1080], upload_to='product-img'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', help_text='Upload image of size 400 x 200', keep_meta=True, quality=70, scale=None, size=[1920, 1080], upload_to='offer'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', help_text='Upload image of size 600 x 600', keep_meta=True, quality=70, scale=None, size=[1920, 1080], upload_to='product-img'),
        ),
    ]
